version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:8.1-fpm
    working_directory: ~/project
    
    steps:
      - checkout
      
      # Install dependencies
      - run:
          name: Install Dependencies
          command: composer update

      # Set up PHPUnit environment
      - run:
          name: Configure PHPUnit
          command: |
            mv .env.example .env
            php artisan key:generate
            php artisan config:cache

      # Run Database Migrations
      - run:
          name: Run Database Migrations
          command: php artisan migrate --force

      # Run Tests
      - run:
          name: Run Tests
          command: php artisan test

workflows:
  version: 2
  build:
    jobs:
      - build
